// Generated by gencpp from file server_client_cpp/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SERVER_CLIENT_CPP_MESSAGE_ADDTWOINTS_H
#define SERVER_CLIENT_CPP_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <server_client_cpp/AddTwoIntsRequest.h>
#include <server_client_cpp/AddTwoIntsResponse.h>


namespace server_client_cpp
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace server_client_cpp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server_client_cpp::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::server_client_cpp::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::server_client_cpp::AddTwoInts > {
  static const char* value()
  {
    return "server_client_cpp/AddTwoInts";
  }

  static const char* value(const ::server_client_cpp::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::server_client_cpp::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::server_client_cpp::AddTwoInts > 
template<>
struct MD5Sum< ::server_client_cpp::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server_client_cpp::AddTwoInts >::value();
  }
  static const char* value(const ::server_client_cpp::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_client_cpp::AddTwoIntsRequest> should match 
// service_traits::DataType< ::server_client_cpp::AddTwoInts > 
template<>
struct DataType< ::server_client_cpp::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::server_client_cpp::AddTwoInts >::value();
  }
  static const char* value(const ::server_client_cpp::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server_client_cpp::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::server_client_cpp::AddTwoInts > 
template<>
struct MD5Sum< ::server_client_cpp::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server_client_cpp::AddTwoInts >::value();
  }
  static const char* value(const ::server_client_cpp::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_client_cpp::AddTwoIntsResponse> should match 
// service_traits::DataType< ::server_client_cpp::AddTwoInts > 
template<>
struct DataType< ::server_client_cpp::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::server_client_cpp::AddTwoInts >::value();
  }
  static const char* value(const ::server_client_cpp::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_CLIENT_CPP_MESSAGE_ADDTWOINTS_H
